// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.12.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -1354039263;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__local_terminal__close_local_terminal_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "close_local_terminal",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok =
                            crate::local_terminal::close_local_terminal(api_session_id)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__ssh_session__close_session_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "close_session",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::ssh_session::close_session(api_session_id)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__ssh_session__connect_profile_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "connect_profile",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_profile_id = <String>::sse_decode(&mut deserializer);
            let api_title = <String>::sse_decode(&mut deserializer);
            let api_host = <String>::sse_decode(&mut deserializer);
            let api_port = <u16>::sse_decode(&mut deserializer);
            let api_username = <String>::sse_decode(&mut deserializer);
            let api_credential =
                <crate::ssh_auth::SshAuthCredential>::sse_decode(&mut deserializer);
            let api_term_type = <String>::sse_decode(&mut deserializer);
            let api_rows = <u16>::sse_decode(&mut deserializer);
            let api_cols = <u16>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::ssh_session::connect_profile(
                            api_profile_id,
                            api_title,
                            api_host,
                            api_port,
                            api_username,
                            api_credential,
                            api_term_type,
                            api_rows,
                            api_cols,
                        )?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__local_terminal__create_local_terminal_output_stream_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "create_local_terminal_output_stream",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <String>::sse_decode(&mut deserializer);
            let api_sink =
                <StreamSink<Vec<u8>, flutter_rust_bridge::for_generated::SseCodec>>::sse_decode(
                    &mut deserializer,
                );
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::local_terminal::create_local_terminal_output_stream(
                            api_session_id,
                            api_sink,
                        );
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__ssh_session__create_output_stream_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "create_output_stream",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <String>::sse_decode(&mut deserializer);
            let api_sink =
                <StreamSink<Vec<u8>, flutter_rust_bridge::for_generated::SseCodec>>::sse_decode(
                    &mut deserializer,
                );
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::ssh_session::create_output_stream(api_session_id, api_sink);
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__profile__create_profile_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "create_profile",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_name = <String>::sse_decode(&mut deserializer);
            let api_host = <String>::sse_decode(&mut deserializer);
            let api_port = <u16>::sse_decode(&mut deserializer);
            let api_username = <String>::sse_decode(&mut deserializer);
            let api_auth_mode = <crate::profile::SshAuthMode>::sse_decode(&mut deserializer);
            let api_password = <String>::sse_decode(&mut deserializer);
            let api_private_key_path = <String>::sse_decode(&mut deserializer);
            let api_term_type = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::profile::create_profile(
                            api_name,
                            api_host,
                            api_port,
                            api_username,
                            api_auth_mode,
                            api_password,
                            api_private_key_path,
                            api_term_type,
                        )?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__tunnel__create_tunnel_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "create_tunnel",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_name = <String>::sse_decode(&mut deserializer);
            let api_forward_type =
                <crate::tunnel::TunnelForwardType>::sse_decode(&mut deserializer);
            let api_ssh_profile_id = <String>::sse_decode(&mut deserializer);
            let api_listen_host = <String>::sse_decode(&mut deserializer);
            let api_listen_port = <u16>::sse_decode(&mut deserializer);
            let api_target_host = <String>::sse_decode(&mut deserializer);
            let api_target_port = <u16>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::tunnel::create_tunnel(
                            api_name,
                            api_forward_type,
                            api_ssh_profile_id,
                            api_listen_host,
                            api_listen_port,
                            api_target_host,
                            api_target_port,
                        )?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__profile__delete_profile_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "delete_profile",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::profile::delete_profile(api_id)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__tunnel__delete_tunnel_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "delete_tunnel",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::tunnel::delete_tunnel(api_id)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__ssh_session__duplicate_session_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "duplicate_session",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::ssh_session::duplicate_session(api_session_id)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__profile__list_profiles_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "list_profiles",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::profile::list_profiles()?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__tunnel__list_tunnels_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "list_tunnels",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::tunnel::list_tunnels()?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__theme__load_theme_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "load_theme",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::theme::load_theme()?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__local_terminal__resize_local_terminal_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "resize_local_terminal",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <String>::sse_decode(&mut deserializer);
            let api_rows = <u16>::sse_decode(&mut deserializer);
            let api_cols = <u16>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::local_terminal::resize_local_terminal(
                            api_session_id,
                            api_rows,
                            api_cols,
                        )?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__ssh_session__resize_session_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "resize_session",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <String>::sse_decode(&mut deserializer);
            let api_rows = <u16>::sse_decode(&mut deserializer);
            let api_cols = <u16>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok =
                            crate::ssh_session::resize_session(api_session_id, api_rows, api_cols)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__mem_metrics__rust_mem_snapshot_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "rust_mem_snapshot",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(crate::mem_metrics::rust_mem_snapshot())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__mem_metrics__rust_mimalloc_collect_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "rust_mimalloc_collect",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::mem_metrics::rust_mimalloc_collect();
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__theme__save_theme_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "save_theme",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_settings = <crate::theme::ThemeSettings>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::theme::save_theme(api_settings)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__local_terminal__spawn_local_terminal_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "spawn_local_terminal",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_rows = <Option<u16>>::sse_decode(&mut deserializer);
            let api_cols = <Option<u16>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok =
                            crate::local_terminal::spawn_local_terminal(api_rows, api_cols)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__tunnel__start_tunnel_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "start_tunnel",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_id = <String>::sse_decode(&mut deserializer);
            let api_credential =
                <crate::ssh_auth::SshAuthCredential>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::tunnel::start_tunnel(api_id, api_credential)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__tunnel__stop_tunnel_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "stop_tunnel",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::tunnel::stop_tunnel(api_id)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__profile__update_profile_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "update_profile",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_id = <String>::sse_decode(&mut deserializer);
            let api_name = <String>::sse_decode(&mut deserializer);
            let api_host = <String>::sse_decode(&mut deserializer);
            let api_port = <u16>::sse_decode(&mut deserializer);
            let api_username = <String>::sse_decode(&mut deserializer);
            let api_auth_mode = <crate::profile::SshAuthMode>::sse_decode(&mut deserializer);
            let api_password = <String>::sse_decode(&mut deserializer);
            let api_private_key_path = <String>::sse_decode(&mut deserializer);
            let api_term_type = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::profile::update_profile(
                            api_id,
                            api_name,
                            api_host,
                            api_port,
                            api_username,
                            api_auth_mode,
                            api_password,
                            api_private_key_path,
                            api_term_type,
                        )?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__tunnel__update_tunnel_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "update_tunnel",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_id = <String>::sse_decode(&mut deserializer);
            let api_name = <String>::sse_decode(&mut deserializer);
            let api_forward_type =
                <crate::tunnel::TunnelForwardType>::sse_decode(&mut deserializer);
            let api_ssh_profile_id = <String>::sse_decode(&mut deserializer);
            let api_listen_host = <String>::sse_decode(&mut deserializer);
            let api_listen_port = <u16>::sse_decode(&mut deserializer);
            let api_target_host = <String>::sse_decode(&mut deserializer);
            let api_target_port = <u16>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::tunnel::update_tunnel(
                            api_id,
                            api_name,
                            api_forward_type,
                            api_ssh_profile_id,
                            api_listen_host,
                            api_listen_port,
                            api_target_host,
                            api_target_port,
                        )?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__local_terminal__write_to_local_terminal_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "write_to_local_terminal",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <String>::sse_decode(&mut deserializer);
            let api_data = <Vec<u8>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::local_terminal::write_to_local_terminal(
                            api_session_id,
                            api_data,
                        )?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__ssh_session__write_to_session_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "write_to_session",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <String>::sse_decode(&mut deserializer);
            let api_data = <Vec<u8>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok =
                            crate::ssh_session::write_to_session(api_session_id, api_data)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);
    }
}

impl SseDecode for StreamSink<Vec<u8>, flutter_rust_bridge::for_generated::SseCodec> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::theme::RegexHighlight> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::theme::RegexHighlight>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::profile::SshProfile> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::profile::SshProfile>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::tunnel::TunnelConfig> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::tunnel::TunnelConfig>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for crate::local_terminal::LocalTerminalSession {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_sessionId = <String>::sse_decode(deserializer);
        let mut var_title = <String>::sse_decode(deserializer);
        return crate::local_terminal::LocalTerminalSession {
            session_id: var_sessionId,
            title: var_title,
        };
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::ssh_auth::SshConnectError> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::ssh_auth::SshConnectError>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::ssh_session::SshSession> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::ssh_session::SshSession>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::tunnel::TunnelConfig> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::tunnel::TunnelConfig>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u16> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u16>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::theme::RegexHighlight {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_pattern = <String>::sse_decode(deserializer);
        let mut var_color = <String>::sse_decode(deserializer);
        let mut var_note = <String>::sse_decode(deserializer);
        return crate::theme::RegexHighlight {
            pattern: var_pattern,
            color: var_color,
            note: var_note,
        };
    }
}

impl SseDecode for crate::mem_metrics::RustMemSnapshot {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_currentRss = <u64>::sse_decode(deserializer);
        let mut var_peakRss = <u64>::sse_decode(deserializer);
        let mut var_currentCommit = <u64>::sse_decode(deserializer);
        let mut var_peakCommit = <u64>::sse_decode(deserializer);
        let mut var_pageFaults = <u64>::sse_decode(deserializer);
        let mut var_elapsedMs = <u64>::sse_decode(deserializer);
        let mut var_userMs = <u64>::sse_decode(deserializer);
        let mut var_systemMs = <u64>::sse_decode(deserializer);
        let mut var_sshSessions = <u64>::sse_decode(deserializer);
        let mut var_sshConnections = <u64>::sse_decode(deserializer);
        let mut var_sshClients = <u64>::sse_decode(deserializer);
        let mut var_localTerminals = <u64>::sse_decode(deserializer);
        let mut var_tunnelConfigs = <u64>::sse_decode(deserializer);
        let mut var_tunnelsRunning = <u64>::sse_decode(deserializer);
        let mut var_mimallocStatsText = <String>::sse_decode(deserializer);
        return crate::mem_metrics::RustMemSnapshot {
            current_rss: var_currentRss,
            peak_rss: var_peakRss,
            current_commit: var_currentCommit,
            peak_commit: var_peakCommit,
            page_faults: var_pageFaults,
            elapsed_ms: var_elapsedMs,
            user_ms: var_userMs,
            system_ms: var_systemMs,
            ssh_sessions: var_sshSessions,
            ssh_connections: var_sshConnections,
            ssh_clients: var_sshClients,
            local_terminals: var_localTerminals,
            tunnel_configs: var_tunnelConfigs,
            tunnels_running: var_tunnelsRunning,
            mimalloc_stats_text: var_mimallocStatsText,
        };
    }
}

impl SseDecode for crate::ssh_auth::SshAuthCredential {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_password = <Option<String>>::sse_decode(deserializer);
        let mut var_privateKeyPath = <Option<String>>::sse_decode(deserializer);
        let mut var_passphrase = <Option<String>>::sse_decode(deserializer);
        return crate::ssh_auth::SshAuthCredential {
            password: var_password,
            private_key_path: var_privateKeyPath,
            passphrase: var_passphrase,
        };
    }
}

impl SseDecode for crate::profile::SshAuthMode {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::profile::SshAuthMode::Password,
            1 => crate::profile::SshAuthMode::PrivateKey,
            _ => unreachable!("Invalid variant for SshAuthMode: {}", inner),
        };
    }
}

impl SseDecode for crate::ssh_auth::SshConnectError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_code = <crate::ssh_auth::SshConnectErrorCode>::sse_decode(deserializer);
        let mut var_message = <String>::sse_decode(deserializer);
        return crate::ssh_auth::SshConnectError {
            code: var_code,
            message: var_message,
        };
    }
}

impl SseDecode for crate::ssh_auth::SshConnectErrorCode {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::ssh_auth::SshConnectErrorCode::PassphraseRequired,
            1 => crate::ssh_auth::SshConnectErrorCode::PrivateKeyFileUnreadable,
            2 => crate::ssh_auth::SshConnectErrorCode::InvalidPrivateKey,
            3 => crate::ssh_auth::SshConnectErrorCode::AuthenticationFailed,
            4 => crate::ssh_auth::SshConnectErrorCode::ConnectionFailed,
            5 => crate::ssh_auth::SshConnectErrorCode::ChannelFailed,
            6 => crate::ssh_auth::SshConnectErrorCode::PtyFailed,
            _ => unreachable!("Invalid variant for SshConnectErrorCode: {}", inner),
        };
    }
}

impl SseDecode for crate::ssh_session::SshConnectResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_session = <Option<crate::ssh_session::SshSession>>::sse_decode(deserializer);
        let mut var_error = <Option<crate::ssh_auth::SshConnectError>>::sse_decode(deserializer);
        return crate::ssh_session::SshConnectResult {
            session: var_session,
            error: var_error,
        };
    }
}

impl SseDecode for crate::profile::SshProfile {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_host = <String>::sse_decode(deserializer);
        let mut var_port = <u16>::sse_decode(deserializer);
        let mut var_username = <String>::sse_decode(deserializer);
        let mut var_authMode = <crate::profile::SshAuthMode>::sse_decode(deserializer);
        let mut var_password = <String>::sse_decode(deserializer);
        let mut var_privateKeyPath = <String>::sse_decode(deserializer);
        let mut var_termType = <String>::sse_decode(deserializer);
        return crate::profile::SshProfile {
            id: var_id,
            name: var_name,
            host: var_host,
            port: var_port,
            username: var_username,
            auth_mode: var_authMode,
            password: var_password,
            private_key_path: var_privateKeyPath,
            term_type: var_termType,
        };
    }
}

impl SseDecode for crate::ssh_session::SshSession {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_sessionId = <String>::sse_decode(deserializer);
        let mut var_profileId = <String>::sse_decode(deserializer);
        let mut var_connectionId = <String>::sse_decode(deserializer);
        let mut var_title = <String>::sse_decode(deserializer);
        let mut var_rows = <u16>::sse_decode(deserializer);
        let mut var_cols = <u16>::sse_decode(deserializer);
        let mut var_termType = <String>::sse_decode(deserializer);
        return crate::ssh_session::SshSession {
            session_id: var_sessionId,
            profile_id: var_profileId,
            connection_id: var_connectionId,
            title: var_title,
            rows: var_rows,
            cols: var_cols,
            term_type: var_termType,
        };
    }
}

impl SseDecode for crate::theme::TerminalTheme {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_presetName = <String>::sse_decode(deserializer);
        let mut var_fontFamily = <String>::sse_decode(deserializer);
        let mut var_fontSize = <u32>::sse_decode(deserializer);
        let mut var_normalFontWeight = <u32>::sse_decode(deserializer);
        let mut var_boldFontWeight = <u32>::sse_decode(deserializer);
        let mut var_cursorStyle = <String>::sse_decode(deserializer);
        let mut var_cursorBlink = <bool>::sse_decode(deserializer);
        let mut var_foreground = <String>::sse_decode(deserializer);
        let mut var_terminalBackground = <String>::sse_decode(deserializer);
        let mut var_selectionColor = <String>::sse_decode(deserializer);
        let mut var_cursorColor = <String>::sse_decode(deserializer);
        let mut var_scrollbackLines = <u32>::sse_decode(deserializer);
        let mut var_regexHighlights = <Vec<crate::theme::RegexHighlight>>::sse_decode(deserializer);
        return crate::theme::TerminalTheme {
            preset_name: var_presetName,
            font_family: var_fontFamily,
            font_size: var_fontSize,
            normal_font_weight: var_normalFontWeight,
            bold_font_weight: var_boldFontWeight,
            cursor_style: var_cursorStyle,
            cursor_blink: var_cursorBlink,
            foreground: var_foreground,
            terminal_background: var_terminalBackground,
            selection_color: var_selectionColor,
            cursor_color: var_cursorColor,
            scrollback_lines: var_scrollbackLines,
            regex_highlights: var_regexHighlights,
        };
    }
}

impl SseDecode for crate::theme::ThemeSettings {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_ui = <crate::theme::UiTheme>::sse_decode(deserializer);
        let mut var_terminal = <crate::theme::TerminalTheme>::sse_decode(deserializer);
        return crate::theme::ThemeSettings {
            ui: var_ui,
            terminal: var_terminal,
        };
    }
}

impl SseDecode for crate::tunnel::TunnelConfig {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_forwardType = <crate::tunnel::TunnelForwardType>::sse_decode(deserializer);
        let mut var_sshProfileId = <String>::sse_decode(deserializer);
        let mut var_listenHost = <String>::sse_decode(deserializer);
        let mut var_listenPort = <u16>::sse_decode(deserializer);
        let mut var_targetHost = <String>::sse_decode(deserializer);
        let mut var_targetPort = <u16>::sse_decode(deserializer);
        let mut var_status = <crate::tunnel::TunnelRuntimeStatus>::sse_decode(deserializer);
        return crate::tunnel::TunnelConfig {
            id: var_id,
            name: var_name,
            forward_type: var_forwardType,
            ssh_profile_id: var_sshProfileId,
            listen_host: var_listenHost,
            listen_port: var_listenPort,
            target_host: var_targetHost,
            target_port: var_targetPort,
            status: var_status,
        };
    }
}

impl SseDecode for crate::tunnel::TunnelForwardType {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::tunnel::TunnelForwardType::Local,
            1 => crate::tunnel::TunnelForwardType::Remote,
            _ => unreachable!("Invalid variant for TunnelForwardType: {}", inner),
        };
    }
}

impl SseDecode for crate::tunnel::TunnelRuntimeStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::tunnel::TunnelRuntimeStatus::Stopped,
            1 => crate::tunnel::TunnelRuntimeStatus::Waiting,
            2 => crate::tunnel::TunnelRuntimeStatus::Forwarding,
            _ => unreachable!("Invalid variant for TunnelRuntimeStatus: {}", inner),
        };
    }
}

impl SseDecode for crate::tunnel::TunnelStartResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_tunnel = <Option<crate::tunnel::TunnelConfig>>::sse_decode(deserializer);
        let mut var_error = <Option<crate::ssh_auth::SshConnectError>>::sse_decode(deserializer);
        return crate::tunnel::TunnelStartResult {
            tunnel: var_tunnel,
            error: var_error,
        };
    }
}

impl SseDecode for u16 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u16::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for crate::theme::UiTheme {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_presetName = <String>::sse_decode(deserializer);
        let mut var_fontFamily = <String>::sse_decode(deserializer);
        let mut var_fontSize = <u32>::sse_decode(deserializer);
        let mut var_normalFontWeight = <u32>::sse_decode(deserializer);
        let mut var_boldFontWeight = <u32>::sse_decode(deserializer);
        let mut var_background = <String>::sse_decode(deserializer);
        let mut var_panel = <String>::sse_decode(deserializer);
        let mut var_sidebar = <String>::sse_decode(deserializer);
        let mut var_accent = <String>::sse_decode(deserializer);
        let mut var_textPrimary = <String>::sse_decode(deserializer);
        let mut var_textMuted = <String>::sse_decode(deserializer);
        return crate::theme::UiTheme {
            preset_name: var_presetName,
            font_family: var_fontFamily,
            font_size: var_fontSize,
            normal_font_weight: var_normalFontWeight,
            bold_font_weight: var_boldFontWeight,
            background: var_background,
            panel: var_panel,
            sidebar: var_sidebar,
            accent: var_accent,
            text_primary: var_textPrimary,
            text_muted: var_textMuted,
        };
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__local_terminal__close_local_terminal_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        2 => wire__crate__ssh_session__close_session_impl(port, ptr, rust_vec_len, data_len),
        3 => wire__crate__ssh_session__connect_profile_impl(port, ptr, rust_vec_len, data_len),
        4 => wire__crate__local_terminal__create_local_terminal_output_stream_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        5 => wire__crate__ssh_session__create_output_stream_impl(port, ptr, rust_vec_len, data_len),
        6 => wire__crate__profile__create_profile_impl(port, ptr, rust_vec_len, data_len),
        7 => wire__crate__tunnel__create_tunnel_impl(port, ptr, rust_vec_len, data_len),
        8 => wire__crate__profile__delete_profile_impl(port, ptr, rust_vec_len, data_len),
        9 => wire__crate__tunnel__delete_tunnel_impl(port, ptr, rust_vec_len, data_len),
        10 => wire__crate__ssh_session__duplicate_session_impl(port, ptr, rust_vec_len, data_len),
        11 => wire__crate__profile__list_profiles_impl(port, ptr, rust_vec_len, data_len),
        12 => wire__crate__tunnel__list_tunnels_impl(port, ptr, rust_vec_len, data_len),
        13 => wire__crate__theme__load_theme_impl(port, ptr, rust_vec_len, data_len),
        14 => wire__crate__local_terminal__resize_local_terminal_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        15 => wire__crate__ssh_session__resize_session_impl(port, ptr, rust_vec_len, data_len),
        16 => wire__crate__mem_metrics__rust_mem_snapshot_impl(port, ptr, rust_vec_len, data_len),
        17 => {
            wire__crate__mem_metrics__rust_mimalloc_collect_impl(port, ptr, rust_vec_len, data_len)
        }
        18 => wire__crate__theme__save_theme_impl(port, ptr, rust_vec_len, data_len),
        19 => wire__crate__local_terminal__spawn_local_terminal_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        20 => wire__crate__tunnel__start_tunnel_impl(port, ptr, rust_vec_len, data_len),
        21 => wire__crate__tunnel__stop_tunnel_impl(port, ptr, rust_vec_len, data_len),
        22 => wire__crate__profile__update_profile_impl(port, ptr, rust_vec_len, data_len),
        23 => wire__crate__tunnel__update_tunnel_impl(port, ptr, rust_vec_len, data_len),
        24 => wire__crate__local_terminal__write_to_local_terminal_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        25 => wire__crate__ssh_session__write_to_session_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::local_terminal::LocalTerminalSession {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.session_id.into_into_dart().into_dart(),
            self.title.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::local_terminal::LocalTerminalSession
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::local_terminal::LocalTerminalSession>
    for crate::local_terminal::LocalTerminalSession
{
    fn into_into_dart(self) -> crate::local_terminal::LocalTerminalSession {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::theme::RegexHighlight {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.pattern.into_into_dart().into_dart(),
            self.color.into_into_dart().into_dart(),
            self.note.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::theme::RegexHighlight {}
impl flutter_rust_bridge::IntoIntoDart<crate::theme::RegexHighlight>
    for crate::theme::RegexHighlight
{
    fn into_into_dart(self) -> crate::theme::RegexHighlight {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::mem_metrics::RustMemSnapshot {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.current_rss.into_into_dart().into_dart(),
            self.peak_rss.into_into_dart().into_dart(),
            self.current_commit.into_into_dart().into_dart(),
            self.peak_commit.into_into_dart().into_dart(),
            self.page_faults.into_into_dart().into_dart(),
            self.elapsed_ms.into_into_dart().into_dart(),
            self.user_ms.into_into_dart().into_dart(),
            self.system_ms.into_into_dart().into_dart(),
            self.ssh_sessions.into_into_dart().into_dart(),
            self.ssh_connections.into_into_dart().into_dart(),
            self.ssh_clients.into_into_dart().into_dart(),
            self.local_terminals.into_into_dart().into_dart(),
            self.tunnel_configs.into_into_dart().into_dart(),
            self.tunnels_running.into_into_dart().into_dart(),
            self.mimalloc_stats_text.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::mem_metrics::RustMemSnapshot
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::mem_metrics::RustMemSnapshot>
    for crate::mem_metrics::RustMemSnapshot
{
    fn into_into_dart(self) -> crate::mem_metrics::RustMemSnapshot {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::ssh_auth::SshAuthCredential {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.password.into_into_dart().into_dart(),
            self.private_key_path.into_into_dart().into_dart(),
            self.passphrase.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::ssh_auth::SshAuthCredential
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::ssh_auth::SshAuthCredential>
    for crate::ssh_auth::SshAuthCredential
{
    fn into_into_dart(self) -> crate::ssh_auth::SshAuthCredential {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::profile::SshAuthMode {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Password => 0.into_dart(),
            Self::PrivateKey => 1.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::profile::SshAuthMode {}
impl flutter_rust_bridge::IntoIntoDart<crate::profile::SshAuthMode>
    for crate::profile::SshAuthMode
{
    fn into_into_dart(self) -> crate::profile::SshAuthMode {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::ssh_auth::SshConnectError {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.code.into_into_dart().into_dart(),
            self.message.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::ssh_auth::SshConnectError
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::ssh_auth::SshConnectError>
    for crate::ssh_auth::SshConnectError
{
    fn into_into_dart(self) -> crate::ssh_auth::SshConnectError {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::ssh_auth::SshConnectErrorCode {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::PassphraseRequired => 0.into_dart(),
            Self::PrivateKeyFileUnreadable => 1.into_dart(),
            Self::InvalidPrivateKey => 2.into_dart(),
            Self::AuthenticationFailed => 3.into_dart(),
            Self::ConnectionFailed => 4.into_dart(),
            Self::ChannelFailed => 5.into_dart(),
            Self::PtyFailed => 6.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::ssh_auth::SshConnectErrorCode
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::ssh_auth::SshConnectErrorCode>
    for crate::ssh_auth::SshConnectErrorCode
{
    fn into_into_dart(self) -> crate::ssh_auth::SshConnectErrorCode {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::ssh_session::SshConnectResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.session.into_into_dart().into_dart(),
            self.error.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::ssh_session::SshConnectResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::ssh_session::SshConnectResult>
    for crate::ssh_session::SshConnectResult
{
    fn into_into_dart(self) -> crate::ssh_session::SshConnectResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::profile::SshProfile {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.name.into_into_dart().into_dart(),
            self.host.into_into_dart().into_dart(),
            self.port.into_into_dart().into_dart(),
            self.username.into_into_dart().into_dart(),
            self.auth_mode.into_into_dart().into_dart(),
            self.password.into_into_dart().into_dart(),
            self.private_key_path.into_into_dart().into_dart(),
            self.term_type.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::profile::SshProfile {}
impl flutter_rust_bridge::IntoIntoDart<crate::profile::SshProfile> for crate::profile::SshProfile {
    fn into_into_dart(self) -> crate::profile::SshProfile {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::ssh_session::SshSession {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.session_id.into_into_dart().into_dart(),
            self.profile_id.into_into_dart().into_dart(),
            self.connection_id.into_into_dart().into_dart(),
            self.title.into_into_dart().into_dart(),
            self.rows.into_into_dart().into_dart(),
            self.cols.into_into_dart().into_dart(),
            self.term_type.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::ssh_session::SshSession
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::ssh_session::SshSession>
    for crate::ssh_session::SshSession
{
    fn into_into_dart(self) -> crate::ssh_session::SshSession {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::theme::TerminalTheme {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.preset_name.into_into_dart().into_dart(),
            self.font_family.into_into_dart().into_dart(),
            self.font_size.into_into_dart().into_dart(),
            self.normal_font_weight.into_into_dart().into_dart(),
            self.bold_font_weight.into_into_dart().into_dart(),
            self.cursor_style.into_into_dart().into_dart(),
            self.cursor_blink.into_into_dart().into_dart(),
            self.foreground.into_into_dart().into_dart(),
            self.terminal_background.into_into_dart().into_dart(),
            self.selection_color.into_into_dart().into_dart(),
            self.cursor_color.into_into_dart().into_dart(),
            self.scrollback_lines.into_into_dart().into_dart(),
            self.regex_highlights.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::theme::TerminalTheme {}
impl flutter_rust_bridge::IntoIntoDart<crate::theme::TerminalTheme>
    for crate::theme::TerminalTheme
{
    fn into_into_dart(self) -> crate::theme::TerminalTheme {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::theme::ThemeSettings {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.ui.into_into_dart().into_dart(),
            self.terminal.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::theme::ThemeSettings {}
impl flutter_rust_bridge::IntoIntoDart<crate::theme::ThemeSettings>
    for crate::theme::ThemeSettings
{
    fn into_into_dart(self) -> crate::theme::ThemeSettings {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::tunnel::TunnelConfig {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.name.into_into_dart().into_dart(),
            self.forward_type.into_into_dart().into_dart(),
            self.ssh_profile_id.into_into_dart().into_dart(),
            self.listen_host.into_into_dart().into_dart(),
            self.listen_port.into_into_dart().into_dart(),
            self.target_host.into_into_dart().into_dart(),
            self.target_port.into_into_dart().into_dart(),
            self.status.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::tunnel::TunnelConfig {}
impl flutter_rust_bridge::IntoIntoDart<crate::tunnel::TunnelConfig>
    for crate::tunnel::TunnelConfig
{
    fn into_into_dart(self) -> crate::tunnel::TunnelConfig {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::tunnel::TunnelForwardType {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Local => 0.into_dart(),
            Self::Remote => 1.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::tunnel::TunnelForwardType
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::tunnel::TunnelForwardType>
    for crate::tunnel::TunnelForwardType
{
    fn into_into_dart(self) -> crate::tunnel::TunnelForwardType {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::tunnel::TunnelRuntimeStatus {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Stopped => 0.into_dart(),
            Self::Waiting => 1.into_dart(),
            Self::Forwarding => 2.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::tunnel::TunnelRuntimeStatus
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::tunnel::TunnelRuntimeStatus>
    for crate::tunnel::TunnelRuntimeStatus
{
    fn into_into_dart(self) -> crate::tunnel::TunnelRuntimeStatus {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::tunnel::TunnelStartResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.tunnel.into_into_dart().into_dart(),
            self.error.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::tunnel::TunnelStartResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::tunnel::TunnelStartResult>
    for crate::tunnel::TunnelStartResult
{
    fn into_into_dart(self) -> crate::tunnel::TunnelStartResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::theme::UiTheme {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.preset_name.into_into_dart().into_dart(),
            self.font_family.into_into_dart().into_dart(),
            self.font_size.into_into_dart().into_dart(),
            self.normal_font_weight.into_into_dart().into_dart(),
            self.bold_font_weight.into_into_dart().into_dart(),
            self.background.into_into_dart().into_dart(),
            self.panel.into_into_dart().into_dart(),
            self.sidebar.into_into_dart().into_dart(),
            self.accent.into_into_dart().into_dart(),
            self.text_primary.into_into_dart().into_dart(),
            self.text_muted.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::theme::UiTheme {}
impl flutter_rust_bridge::IntoIntoDart<crate::theme::UiTheme> for crate::theme::UiTheme {
    fn into_into_dart(self) -> crate::theme::UiTheme {
        self
    }
}

impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(format!("{:?}", self), serializer);
    }
}

impl SseEncode for StreamSink<Vec<u8>, flutter_rust_bridge::for_generated::SseCodec> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::theme::RegexHighlight> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::theme::RegexHighlight>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::profile::SshProfile> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::profile::SshProfile>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::tunnel::TunnelConfig> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::tunnel::TunnelConfig>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for crate::local_terminal::LocalTerminalSession {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.session_id, serializer);
        <String>::sse_encode(self.title, serializer);
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::ssh_auth::SshConnectError> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::ssh_auth::SshConnectError>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::ssh_session::SshSession> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::ssh_session::SshSession>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::tunnel::TunnelConfig> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::tunnel::TunnelConfig>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u16> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u16>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::theme::RegexHighlight {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.pattern, serializer);
        <String>::sse_encode(self.color, serializer);
        <String>::sse_encode(self.note, serializer);
    }
}

impl SseEncode for crate::mem_metrics::RustMemSnapshot {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u64>::sse_encode(self.current_rss, serializer);
        <u64>::sse_encode(self.peak_rss, serializer);
        <u64>::sse_encode(self.current_commit, serializer);
        <u64>::sse_encode(self.peak_commit, serializer);
        <u64>::sse_encode(self.page_faults, serializer);
        <u64>::sse_encode(self.elapsed_ms, serializer);
        <u64>::sse_encode(self.user_ms, serializer);
        <u64>::sse_encode(self.system_ms, serializer);
        <u64>::sse_encode(self.ssh_sessions, serializer);
        <u64>::sse_encode(self.ssh_connections, serializer);
        <u64>::sse_encode(self.ssh_clients, serializer);
        <u64>::sse_encode(self.local_terminals, serializer);
        <u64>::sse_encode(self.tunnel_configs, serializer);
        <u64>::sse_encode(self.tunnels_running, serializer);
        <String>::sse_encode(self.mimalloc_stats_text, serializer);
    }
}

impl SseEncode for crate::ssh_auth::SshAuthCredential {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Option<String>>::sse_encode(self.password, serializer);
        <Option<String>>::sse_encode(self.private_key_path, serializer);
        <Option<String>>::sse_encode(self.passphrase, serializer);
    }
}

impl SseEncode for crate::profile::SshAuthMode {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::profile::SshAuthMode::Password => 0,
                crate::profile::SshAuthMode::PrivateKey => 1,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::ssh_auth::SshConnectError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::ssh_auth::SshConnectErrorCode>::sse_encode(self.code, serializer);
        <String>::sse_encode(self.message, serializer);
    }
}

impl SseEncode for crate::ssh_auth::SshConnectErrorCode {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::ssh_auth::SshConnectErrorCode::PassphraseRequired => 0,
                crate::ssh_auth::SshConnectErrorCode::PrivateKeyFileUnreadable => 1,
                crate::ssh_auth::SshConnectErrorCode::InvalidPrivateKey => 2,
                crate::ssh_auth::SshConnectErrorCode::AuthenticationFailed => 3,
                crate::ssh_auth::SshConnectErrorCode::ConnectionFailed => 4,
                crate::ssh_auth::SshConnectErrorCode::ChannelFailed => 5,
                crate::ssh_auth::SshConnectErrorCode::PtyFailed => 6,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::ssh_session::SshConnectResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Option<crate::ssh_session::SshSession>>::sse_encode(self.session, serializer);
        <Option<crate::ssh_auth::SshConnectError>>::sse_encode(self.error, serializer);
    }
}

impl SseEncode for crate::profile::SshProfile {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.name, serializer);
        <String>::sse_encode(self.host, serializer);
        <u16>::sse_encode(self.port, serializer);
        <String>::sse_encode(self.username, serializer);
        <crate::profile::SshAuthMode>::sse_encode(self.auth_mode, serializer);
        <String>::sse_encode(self.password, serializer);
        <String>::sse_encode(self.private_key_path, serializer);
        <String>::sse_encode(self.term_type, serializer);
    }
}

impl SseEncode for crate::ssh_session::SshSession {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.session_id, serializer);
        <String>::sse_encode(self.profile_id, serializer);
        <String>::sse_encode(self.connection_id, serializer);
        <String>::sse_encode(self.title, serializer);
        <u16>::sse_encode(self.rows, serializer);
        <u16>::sse_encode(self.cols, serializer);
        <String>::sse_encode(self.term_type, serializer);
    }
}

impl SseEncode for crate::theme::TerminalTheme {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.preset_name, serializer);
        <String>::sse_encode(self.font_family, serializer);
        <u32>::sse_encode(self.font_size, serializer);
        <u32>::sse_encode(self.normal_font_weight, serializer);
        <u32>::sse_encode(self.bold_font_weight, serializer);
        <String>::sse_encode(self.cursor_style, serializer);
        <bool>::sse_encode(self.cursor_blink, serializer);
        <String>::sse_encode(self.foreground, serializer);
        <String>::sse_encode(self.terminal_background, serializer);
        <String>::sse_encode(self.selection_color, serializer);
        <String>::sse_encode(self.cursor_color, serializer);
        <u32>::sse_encode(self.scrollback_lines, serializer);
        <Vec<crate::theme::RegexHighlight>>::sse_encode(self.regex_highlights, serializer);
    }
}

impl SseEncode for crate::theme::ThemeSettings {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::theme::UiTheme>::sse_encode(self.ui, serializer);
        <crate::theme::TerminalTheme>::sse_encode(self.terminal, serializer);
    }
}

impl SseEncode for crate::tunnel::TunnelConfig {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.name, serializer);
        <crate::tunnel::TunnelForwardType>::sse_encode(self.forward_type, serializer);
        <String>::sse_encode(self.ssh_profile_id, serializer);
        <String>::sse_encode(self.listen_host, serializer);
        <u16>::sse_encode(self.listen_port, serializer);
        <String>::sse_encode(self.target_host, serializer);
        <u16>::sse_encode(self.target_port, serializer);
        <crate::tunnel::TunnelRuntimeStatus>::sse_encode(self.status, serializer);
    }
}

impl SseEncode for crate::tunnel::TunnelForwardType {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::tunnel::TunnelForwardType::Local => 0,
                crate::tunnel::TunnelForwardType::Remote => 1,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::tunnel::TunnelRuntimeStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::tunnel::TunnelRuntimeStatus::Stopped => 0,
                crate::tunnel::TunnelRuntimeStatus::Waiting => 1,
                crate::tunnel::TunnelRuntimeStatus::Forwarding => 2,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::tunnel::TunnelStartResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Option<crate::tunnel::TunnelConfig>>::sse_encode(self.tunnel, serializer);
        <Option<crate::ssh_auth::SshConnectError>>::sse_encode(self.error, serializer);
    }
}

impl SseEncode for u16 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u16::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for crate::theme::UiTheme {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.preset_name, serializer);
        <String>::sse_encode(self.font_family, serializer);
        <u32>::sse_encode(self.font_size, serializer);
        <u32>::sse_encode(self.normal_font_weight, serializer);
        <u32>::sse_encode(self.bold_font_weight, serializer);
        <String>::sse_encode(self.background, serializer);
        <String>::sse_encode(self.panel, serializer);
        <String>::sse_encode(self.sidebar, serializer);
        <String>::sse_encode(self.accent, serializer);
        <String>::sse_encode(self.text_primary, serializer);
        <String>::sse_encode(self.text_muted, serializer);
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
