// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'local_terminal.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'profile.dart';
import 'ssh_auth.dart';
import 'ssh_session.dart';
import 'theme.dart';
import 'tunnel.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1567238282;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'deepssh_rust',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateLocalTerminalCloseLocalTerminal({
    required String sessionId,
  });

  Future<bool> crateSshSessionCloseSession({required String sessionId});

  Future<SshConnectResult> crateSshSessionConnectProfile({
    required String profileId,
    required String title,
    required String host,
    required int port,
    required String username,
    required SshAuthCredential credential,
    required String termType,
    required int rows,
    required int cols,
  });

  Stream<Uint8List> crateLocalTerminalCreateLocalTerminalOutputStream({
    required String sessionId,
  });

  Stream<Uint8List> crateSshSessionCreateOutputStream({
    required String sessionId,
  });

  Future<SshProfile> crateProfileCreateProfile({
    required String name,
    required String host,
    required int port,
    required String username,
    required SshAuthMode authMode,
    required String password,
    required String privateKeyPath,
    required String termType,
  });

  Future<TunnelConfig> crateTunnelCreateTunnel({
    required String name,
    required TunnelForwardType forwardType,
    required String sshProfileId,
    required String listenHost,
    required int listenPort,
    required String targetHost,
    required int targetPort,
  });

  Future<void> crateProfileDeleteProfile({required String id});

  Future<void> crateTunnelDeleteTunnel({required String id});

  Future<SshSession> crateSshSessionDuplicateSession({
    required String sessionId,
  });

  Future<List<SshProfile>> crateProfileListProfiles();

  Future<List<TunnelConfig>> crateTunnelListTunnels();

  Future<ThemeSettings> crateThemeLoadTheme();

  Future<void> crateLocalTerminalResizeLocalTerminal({
    required String sessionId,
    required int rows,
    required int cols,
  });

  Future<void> crateSshSessionResizeSession({
    required String sessionId,
    required int rows,
    required int cols,
  });

  Future<void> crateThemeSaveTheme({required ThemeSettings settings});

  Future<LocalTerminalSession> crateLocalTerminalSpawnLocalTerminal({
    int? rows,
    int? cols,
  });

  Future<TunnelStartResult> crateTunnelStartTunnel({
    required String id,
    required SshAuthCredential credential,
  });

  Future<TunnelConfig> crateTunnelStopTunnel({required String id});

  Future<SshProfile> crateProfileUpdateProfile({
    required String id,
    required String name,
    required String host,
    required int port,
    required String username,
    required SshAuthMode authMode,
    required String password,
    required String privateKeyPath,
    required String termType,
  });

  Future<TunnelConfig> crateTunnelUpdateTunnel({
    required String id,
    required String name,
    required TunnelForwardType forwardType,
    required String sshProfileId,
    required String listenHost,
    required int listenPort,
    required String targetHost,
    required int targetPort,
  });

  Future<void> crateLocalTerminalWriteToLocalTerminal({
    required String sessionId,
    required List<int> data,
  });

  Future<void> crateSshSessionWriteToSession({
    required String sessionId,
    required List<int> data,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateLocalTerminalCloseLocalTerminal({
    required String sessionId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateLocalTerminalCloseLocalTerminalConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateLocalTerminalCloseLocalTerminalConstMeta =>
      const TaskConstMeta(
        debugName: "close_local_terminal",
        argNames: ["sessionId"],
      );

  @override
  Future<bool> crateSshSessionCloseSession({required String sessionId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateSshSessionCloseSessionConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSshSessionCloseSessionConstMeta =>
      const TaskConstMeta(debugName: "close_session", argNames: ["sessionId"]);

  @override
  Future<SshConnectResult> crateSshSessionConnectProfile({
    required String profileId,
    required String title,
    required String host,
    required int port,
    required String username,
    required SshAuthCredential credential,
    required String termType,
    required int rows,
    required int cols,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(profileId, serializer);
          sse_encode_String(title, serializer);
          sse_encode_String(host, serializer);
          sse_encode_u_16(port, serializer);
          sse_encode_String(username, serializer);
          sse_encode_box_autoadd_ssh_auth_credential(credential, serializer);
          sse_encode_String(termType, serializer);
          sse_encode_u_16(rows, serializer);
          sse_encode_u_16(cols, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ssh_connect_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateSshSessionConnectProfileConstMeta,
        argValues: [
          profileId,
          title,
          host,
          port,
          username,
          credential,
          termType,
          rows,
          cols,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSshSessionConnectProfileConstMeta =>
      const TaskConstMeta(
        debugName: "connect_profile",
        argNames: [
          "profileId",
          "title",
          "host",
          "port",
          "username",
          "credential",
          "termType",
          "rows",
          "cols",
        ],
      );

  @override
  Stream<Uint8List> crateLocalTerminalCreateLocalTerminalOutputStream({
    required String sessionId,
  }) {
    final sink = RustStreamSink<Uint8List>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(sessionId, serializer);
            sse_encode_StreamSink_list_prim_u_8_strict_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 4,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta:
              kCrateLocalTerminalCreateLocalTerminalOutputStreamConstMeta,
          argValues: [sessionId, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta
  get kCrateLocalTerminalCreateLocalTerminalOutputStreamConstMeta =>
      const TaskConstMeta(
        debugName: "create_local_terminal_output_stream",
        argNames: ["sessionId", "sink"],
      );

  @override
  Stream<Uint8List> crateSshSessionCreateOutputStream({
    required String sessionId,
  }) {
    final sink = RustStreamSink<Uint8List>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(sessionId, serializer);
            sse_encode_StreamSink_list_prim_u_8_strict_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 5,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateSshSessionCreateOutputStreamConstMeta,
          argValues: [sessionId, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateSshSessionCreateOutputStreamConstMeta =>
      const TaskConstMeta(
        debugName: "create_output_stream",
        argNames: ["sessionId", "sink"],
      );

  @override
  Future<SshProfile> crateProfileCreateProfile({
    required String name,
    required String host,
    required int port,
    required String username,
    required SshAuthMode authMode,
    required String password,
    required String privateKeyPath,
    required String termType,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_String(host, serializer);
          sse_encode_u_16(port, serializer);
          sse_encode_String(username, serializer);
          sse_encode_ssh_auth_mode(authMode, serializer);
          sse_encode_String(password, serializer);
          sse_encode_String(privateKeyPath, serializer);
          sse_encode_String(termType, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ssh_profile,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateProfileCreateProfileConstMeta,
        argValues: [
          name,
          host,
          port,
          username,
          authMode,
          password,
          privateKeyPath,
          termType,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateProfileCreateProfileConstMeta => const TaskConstMeta(
    debugName: "create_profile",
    argNames: [
      "name",
      "host",
      "port",
      "username",
      "authMode",
      "password",
      "privateKeyPath",
      "termType",
    ],
  );

  @override
  Future<TunnelConfig> crateTunnelCreateTunnel({
    required String name,
    required TunnelForwardType forwardType,
    required String sshProfileId,
    required String listenHost,
    required int listenPort,
    required String targetHost,
    required int targetPort,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_tunnel_forward_type(forwardType, serializer);
          sse_encode_String(sshProfileId, serializer);
          sse_encode_String(listenHost, serializer);
          sse_encode_u_16(listenPort, serializer);
          sse_encode_String(targetHost, serializer);
          sse_encode_u_16(targetPort, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_tunnel_config,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateTunnelCreateTunnelConstMeta,
        argValues: [
          name,
          forwardType,
          sshProfileId,
          listenHost,
          listenPort,
          targetHost,
          targetPort,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateTunnelCreateTunnelConstMeta => const TaskConstMeta(
    debugName: "create_tunnel",
    argNames: [
      "name",
      "forwardType",
      "sshProfileId",
      "listenHost",
      "listenPort",
      "targetHost",
      "targetPort",
    ],
  );

  @override
  Future<void> crateProfileDeleteProfile({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateProfileDeleteProfileConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateProfileDeleteProfileConstMeta =>
      const TaskConstMeta(debugName: "delete_profile", argNames: ["id"]);

  @override
  Future<void> crateTunnelDeleteTunnel({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateTunnelDeleteTunnelConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateTunnelDeleteTunnelConstMeta =>
      const TaskConstMeta(debugName: "delete_tunnel", argNames: ["id"]);

  @override
  Future<SshSession> crateSshSessionDuplicateSession({
    required String sessionId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ssh_session,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateSshSessionDuplicateSessionConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSshSessionDuplicateSessionConstMeta =>
      const TaskConstMeta(
        debugName: "duplicate_session",
        argNames: ["sessionId"],
      );

  @override
  Future<List<SshProfile>> crateProfileListProfiles() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_ssh_profile,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateProfileListProfilesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateProfileListProfilesConstMeta =>
      const TaskConstMeta(debugName: "list_profiles", argNames: []);

  @override
  Future<List<TunnelConfig>> crateTunnelListTunnels() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_tunnel_config,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateTunnelListTunnelsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateTunnelListTunnelsConstMeta =>
      const TaskConstMeta(debugName: "list_tunnels", argNames: []);

  @override
  Future<ThemeSettings> crateThemeLoadTheme() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_theme_settings,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateThemeLoadThemeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateThemeLoadThemeConstMeta =>
      const TaskConstMeta(debugName: "load_theme", argNames: []);

  @override
  Future<void> crateLocalTerminalResizeLocalTerminal({
    required String sessionId,
    required int rows,
    required int cols,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_u_16(rows, serializer);
          sse_encode_u_16(cols, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateLocalTerminalResizeLocalTerminalConstMeta,
        argValues: [sessionId, rows, cols],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateLocalTerminalResizeLocalTerminalConstMeta =>
      const TaskConstMeta(
        debugName: "resize_local_terminal",
        argNames: ["sessionId", "rows", "cols"],
      );

  @override
  Future<void> crateSshSessionResizeSession({
    required String sessionId,
    required int rows,
    required int cols,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_u_16(rows, serializer);
          sse_encode_u_16(cols, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateSshSessionResizeSessionConstMeta,
        argValues: [sessionId, rows, cols],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSshSessionResizeSessionConstMeta =>
      const TaskConstMeta(
        debugName: "resize_session",
        argNames: ["sessionId", "rows", "cols"],
      );

  @override
  Future<void> crateThemeSaveTheme({required ThemeSettings settings}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_theme_settings(settings, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateThemeSaveThemeConstMeta,
        argValues: [settings],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateThemeSaveThemeConstMeta =>
      const TaskConstMeta(debugName: "save_theme", argNames: ["settings"]);

  @override
  Future<LocalTerminalSession> crateLocalTerminalSpawnLocalTerminal({
    int? rows,
    int? cols,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_box_autoadd_u_16(rows, serializer);
          sse_encode_opt_box_autoadd_u_16(cols, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_local_terminal_session,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateLocalTerminalSpawnLocalTerminalConstMeta,
        argValues: [rows, cols],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateLocalTerminalSpawnLocalTerminalConstMeta =>
      const TaskConstMeta(
        debugName: "spawn_local_terminal",
        argNames: ["rows", "cols"],
      );

  @override
  Future<TunnelStartResult> crateTunnelStartTunnel({
    required String id,
    required SshAuthCredential credential,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          sse_encode_box_autoadd_ssh_auth_credential(credential, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_tunnel_start_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateTunnelStartTunnelConstMeta,
        argValues: [id, credential],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateTunnelStartTunnelConstMeta => const TaskConstMeta(
    debugName: "start_tunnel",
    argNames: ["id", "credential"],
  );

  @override
  Future<TunnelConfig> crateTunnelStopTunnel({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_tunnel_config,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateTunnelStopTunnelConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateTunnelStopTunnelConstMeta =>
      const TaskConstMeta(debugName: "stop_tunnel", argNames: ["id"]);

  @override
  Future<SshProfile> crateProfileUpdateProfile({
    required String id,
    required String name,
    required String host,
    required int port,
    required String username,
    required SshAuthMode authMode,
    required String password,
    required String privateKeyPath,
    required String termType,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          sse_encode_String(name, serializer);
          sse_encode_String(host, serializer);
          sse_encode_u_16(port, serializer);
          sse_encode_String(username, serializer);
          sse_encode_ssh_auth_mode(authMode, serializer);
          sse_encode_String(password, serializer);
          sse_encode_String(privateKeyPath, serializer);
          sse_encode_String(termType, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ssh_profile,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateProfileUpdateProfileConstMeta,
        argValues: [
          id,
          name,
          host,
          port,
          username,
          authMode,
          password,
          privateKeyPath,
          termType,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateProfileUpdateProfileConstMeta => const TaskConstMeta(
    debugName: "update_profile",
    argNames: [
      "id",
      "name",
      "host",
      "port",
      "username",
      "authMode",
      "password",
      "privateKeyPath",
      "termType",
    ],
  );

  @override
  Future<TunnelConfig> crateTunnelUpdateTunnel({
    required String id,
    required String name,
    required TunnelForwardType forwardType,
    required String sshProfileId,
    required String listenHost,
    required int listenPort,
    required String targetHost,
    required int targetPort,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          sse_encode_String(name, serializer);
          sse_encode_tunnel_forward_type(forwardType, serializer);
          sse_encode_String(sshProfileId, serializer);
          sse_encode_String(listenHost, serializer);
          sse_encode_u_16(listenPort, serializer);
          sse_encode_String(targetHost, serializer);
          sse_encode_u_16(targetPort, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_tunnel_config,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateTunnelUpdateTunnelConstMeta,
        argValues: [
          id,
          name,
          forwardType,
          sshProfileId,
          listenHost,
          listenPort,
          targetHost,
          targetPort,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateTunnelUpdateTunnelConstMeta => const TaskConstMeta(
    debugName: "update_tunnel",
    argNames: [
      "id",
      "name",
      "forwardType",
      "sshProfileId",
      "listenHost",
      "listenPort",
      "targetHost",
      "targetPort",
    ],
  );

  @override
  Future<void> crateLocalTerminalWriteToLocalTerminal({
    required String sessionId,
    required List<int> data,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateLocalTerminalWriteToLocalTerminalConstMeta,
        argValues: [sessionId, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateLocalTerminalWriteToLocalTerminalConstMeta =>
      const TaskConstMeta(
        debugName: "write_to_local_terminal",
        argNames: ["sessionId", "data"],
      );

  @override
  Future<void> crateSshSessionWriteToSession({
    required String sessionId,
    required List<int> data,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateSshSessionWriteToSessionConstMeta,
        argValues: [sessionId, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSshSessionWriteToSessionConstMeta =>
      const TaskConstMeta(
        debugName: "write_to_session",
        argNames: ["sessionId", "data"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<Uint8List> dco_decode_StreamSink_list_prim_u_8_strict_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  SshAuthCredential dco_decode_box_autoadd_ssh_auth_credential(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_ssh_auth_credential(raw);
  }

  @protected
  SshConnectError dco_decode_box_autoadd_ssh_connect_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_ssh_connect_error(raw);
  }

  @protected
  SshSession dco_decode_box_autoadd_ssh_session(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_ssh_session(raw);
  }

  @protected
  ThemeSettings dco_decode_box_autoadd_theme_settings(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_theme_settings(raw);
  }

  @protected
  TunnelConfig dco_decode_box_autoadd_tunnel_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_tunnel_config(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RegexHighlight> dco_decode_list_regex_highlight(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_regex_highlight).toList();
  }

  @protected
  List<SshProfile> dco_decode_list_ssh_profile(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_ssh_profile).toList();
  }

  @protected
  List<TunnelConfig> dco_decode_list_tunnel_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_tunnel_config).toList();
  }

  @protected
  LocalTerminalSession dco_decode_local_terminal_session(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return LocalTerminalSession(
      sessionId: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  SshConnectError? dco_decode_opt_box_autoadd_ssh_connect_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_ssh_connect_error(raw);
  }

  @protected
  SshSession? dco_decode_opt_box_autoadd_ssh_session(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_ssh_session(raw);
  }

  @protected
  TunnelConfig? dco_decode_opt_box_autoadd_tunnel_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_tunnel_config(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_16(raw);
  }

  @protected
  RegexHighlight dco_decode_regex_highlight(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return RegexHighlight(
      pattern: dco_decode_String(arr[0]),
      color: dco_decode_String(arr[1]),
      note: dco_decode_String(arr[2]),
    );
  }

  @protected
  SshAuthCredential dco_decode_ssh_auth_credential(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SshAuthCredential(
      password: dco_decode_opt_String(arr[0]),
      privateKeyPath: dco_decode_opt_String(arr[1]),
      passphrase: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  SshAuthMode dco_decode_ssh_auth_mode(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SshAuthMode.values[raw as int];
  }

  @protected
  SshConnectError dco_decode_ssh_connect_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SshConnectError(
      code: dco_decode_ssh_connect_error_code(arr[0]),
      message: dco_decode_String(arr[1]),
    );
  }

  @protected
  SshConnectErrorCode dco_decode_ssh_connect_error_code(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SshConnectErrorCode.values[raw as int];
  }

  @protected
  SshConnectResult dco_decode_ssh_connect_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SshConnectResult(
      session: dco_decode_opt_box_autoadd_ssh_session(arr[0]),
      error: dco_decode_opt_box_autoadd_ssh_connect_error(arr[1]),
    );
  }

  @protected
  SshProfile dco_decode_ssh_profile(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return SshProfile(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      host: dco_decode_String(arr[2]),
      port: dco_decode_u_16(arr[3]),
      username: dco_decode_String(arr[4]),
      authMode: dco_decode_ssh_auth_mode(arr[5]),
      password: dco_decode_String(arr[6]),
      privateKeyPath: dco_decode_String(arr[7]),
      termType: dco_decode_String(arr[8]),
    );
  }

  @protected
  SshSession dco_decode_ssh_session(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return SshSession(
      sessionId: dco_decode_String(arr[0]),
      profileId: dco_decode_String(arr[1]),
      connectionId: dco_decode_String(arr[2]),
      title: dco_decode_String(arr[3]),
      rows: dco_decode_u_16(arr[4]),
      cols: dco_decode_u_16(arr[5]),
      termType: dco_decode_String(arr[6]),
    );
  }

  @protected
  TerminalTheme dco_decode_terminal_theme(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 13)
      throw Exception('unexpected arr length: expect 13 but see ${arr.length}');
    return TerminalTheme(
      presetName: dco_decode_String(arr[0]),
      fontFamily: dco_decode_String(arr[1]),
      fontSize: dco_decode_u_32(arr[2]),
      normalFontWeight: dco_decode_u_32(arr[3]),
      boldFontWeight: dco_decode_u_32(arr[4]),
      cursorStyle: dco_decode_String(arr[5]),
      cursorBlink: dco_decode_bool(arr[6]),
      foreground: dco_decode_String(arr[7]),
      terminalBackground: dco_decode_String(arr[8]),
      selectionColor: dco_decode_String(arr[9]),
      cursorColor: dco_decode_String(arr[10]),
      scrollbackLines: dco_decode_u_32(arr[11]),
      regexHighlights: dco_decode_list_regex_highlight(arr[12]),
    );
  }

  @protected
  ThemeSettings dco_decode_theme_settings(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ThemeSettings(
      ui: dco_decode_ui_theme(arr[0]),
      terminal: dco_decode_terminal_theme(arr[1]),
    );
  }

  @protected
  TunnelConfig dco_decode_tunnel_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return TunnelConfig(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      forwardType: dco_decode_tunnel_forward_type(arr[2]),
      sshProfileId: dco_decode_String(arr[3]),
      listenHost: dco_decode_String(arr[4]),
      listenPort: dco_decode_u_16(arr[5]),
      targetHost: dco_decode_String(arr[6]),
      targetPort: dco_decode_u_16(arr[7]),
      status: dco_decode_tunnel_runtime_status(arr[8]),
    );
  }

  @protected
  TunnelForwardType dco_decode_tunnel_forward_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TunnelForwardType.values[raw as int];
  }

  @protected
  TunnelRuntimeStatus dco_decode_tunnel_runtime_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TunnelRuntimeStatus.values[raw as int];
  }

  @protected
  TunnelStartResult dco_decode_tunnel_start_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return TunnelStartResult(
      tunnel: dco_decode_opt_box_autoadd_tunnel_config(arr[0]),
      error: dco_decode_opt_box_autoadd_ssh_connect_error(arr[1]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  UiTheme dco_decode_ui_theme(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return UiTheme(
      presetName: dco_decode_String(arr[0]),
      fontFamily: dco_decode_String(arr[1]),
      fontSize: dco_decode_u_32(arr[2]),
      normalFontWeight: dco_decode_u_32(arr[3]),
      boldFontWeight: dco_decode_u_32(arr[4]),
      background: dco_decode_String(arr[5]),
      panel: dco_decode_String(arr[6]),
      sidebar: dco_decode_String(arr[7]),
      accent: dco_decode_String(arr[8]),
      textPrimary: dco_decode_String(arr[9]),
      textMuted: dco_decode_String(arr[10]),
    );
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<Uint8List> sse_decode_StreamSink_list_prim_u_8_strict_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  SshAuthCredential sse_decode_box_autoadd_ssh_auth_credential(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_ssh_auth_credential(deserializer));
  }

  @protected
  SshConnectError sse_decode_box_autoadd_ssh_connect_error(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_ssh_connect_error(deserializer));
  }

  @protected
  SshSession sse_decode_box_autoadd_ssh_session(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_ssh_session(deserializer));
  }

  @protected
  ThemeSettings sse_decode_box_autoadd_theme_settings(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_theme_settings(deserializer));
  }

  @protected
  TunnelConfig sse_decode_box_autoadd_tunnel_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_tunnel_config(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_16(deserializer));
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RegexHighlight> sse_decode_list_regex_highlight(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RegexHighlight>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_regex_highlight(deserializer));
    }
    return ans_;
  }

  @protected
  List<SshProfile> sse_decode_list_ssh_profile(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SshProfile>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_ssh_profile(deserializer));
    }
    return ans_;
  }

  @protected
  List<TunnelConfig> sse_decode_list_tunnel_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TunnelConfig>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_tunnel_config(deserializer));
    }
    return ans_;
  }

  @protected
  LocalTerminalSession sse_decode_local_terminal_session(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionId = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    return LocalTerminalSession(sessionId: var_sessionId, title: var_title);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SshConnectError? sse_decode_opt_box_autoadd_ssh_connect_error(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_ssh_connect_error(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SshSession? sse_decode_opt_box_autoadd_ssh_session(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_ssh_session(deserializer));
    } else {
      return null;
    }
  }

  @protected
  TunnelConfig? sse_decode_opt_box_autoadd_tunnel_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_tunnel_config(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_16(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RegexHighlight sse_decode_regex_highlight(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_pattern = sse_decode_String(deserializer);
    var var_color = sse_decode_String(deserializer);
    var var_note = sse_decode_String(deserializer);
    return RegexHighlight(
      pattern: var_pattern,
      color: var_color,
      note: var_note,
    );
  }

  @protected
  SshAuthCredential sse_decode_ssh_auth_credential(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_password = sse_decode_opt_String(deserializer);
    var var_privateKeyPath = sse_decode_opt_String(deserializer);
    var var_passphrase = sse_decode_opt_String(deserializer);
    return SshAuthCredential(
      password: var_password,
      privateKeyPath: var_privateKeyPath,
      passphrase: var_passphrase,
    );
  }

  @protected
  SshAuthMode sse_decode_ssh_auth_mode(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SshAuthMode.values[inner];
  }

  @protected
  SshConnectError sse_decode_ssh_connect_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_code = sse_decode_ssh_connect_error_code(deserializer);
    var var_message = sse_decode_String(deserializer);
    return SshConnectError(code: var_code, message: var_message);
  }

  @protected
  SshConnectErrorCode sse_decode_ssh_connect_error_code(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SshConnectErrorCode.values[inner];
  }

  @protected
  SshConnectResult sse_decode_ssh_connect_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_session = sse_decode_opt_box_autoadd_ssh_session(deserializer);
    var var_error = sse_decode_opt_box_autoadd_ssh_connect_error(deserializer);
    return SshConnectResult(session: var_session, error: var_error);
  }

  @protected
  SshProfile sse_decode_ssh_profile(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_host = sse_decode_String(deserializer);
    var var_port = sse_decode_u_16(deserializer);
    var var_username = sse_decode_String(deserializer);
    var var_authMode = sse_decode_ssh_auth_mode(deserializer);
    var var_password = sse_decode_String(deserializer);
    var var_privateKeyPath = sse_decode_String(deserializer);
    var var_termType = sse_decode_String(deserializer);
    return SshProfile(
      id: var_id,
      name: var_name,
      host: var_host,
      port: var_port,
      username: var_username,
      authMode: var_authMode,
      password: var_password,
      privateKeyPath: var_privateKeyPath,
      termType: var_termType,
    );
  }

  @protected
  SshSession sse_decode_ssh_session(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionId = sse_decode_String(deserializer);
    var var_profileId = sse_decode_String(deserializer);
    var var_connectionId = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_rows = sse_decode_u_16(deserializer);
    var var_cols = sse_decode_u_16(deserializer);
    var var_termType = sse_decode_String(deserializer);
    return SshSession(
      sessionId: var_sessionId,
      profileId: var_profileId,
      connectionId: var_connectionId,
      title: var_title,
      rows: var_rows,
      cols: var_cols,
      termType: var_termType,
    );
  }

  @protected
  TerminalTheme sse_decode_terminal_theme(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_presetName = sse_decode_String(deserializer);
    var var_fontFamily = sse_decode_String(deserializer);
    var var_fontSize = sse_decode_u_32(deserializer);
    var var_normalFontWeight = sse_decode_u_32(deserializer);
    var var_boldFontWeight = sse_decode_u_32(deserializer);
    var var_cursorStyle = sse_decode_String(deserializer);
    var var_cursorBlink = sse_decode_bool(deserializer);
    var var_foreground = sse_decode_String(deserializer);
    var var_terminalBackground = sse_decode_String(deserializer);
    var var_selectionColor = sse_decode_String(deserializer);
    var var_cursorColor = sse_decode_String(deserializer);
    var var_scrollbackLines = sse_decode_u_32(deserializer);
    var var_regexHighlights = sse_decode_list_regex_highlight(deserializer);
    return TerminalTheme(
      presetName: var_presetName,
      fontFamily: var_fontFamily,
      fontSize: var_fontSize,
      normalFontWeight: var_normalFontWeight,
      boldFontWeight: var_boldFontWeight,
      cursorStyle: var_cursorStyle,
      cursorBlink: var_cursorBlink,
      foreground: var_foreground,
      terminalBackground: var_terminalBackground,
      selectionColor: var_selectionColor,
      cursorColor: var_cursorColor,
      scrollbackLines: var_scrollbackLines,
      regexHighlights: var_regexHighlights,
    );
  }

  @protected
  ThemeSettings sse_decode_theme_settings(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ui = sse_decode_ui_theme(deserializer);
    var var_terminal = sse_decode_terminal_theme(deserializer);
    return ThemeSettings(ui: var_ui, terminal: var_terminal);
  }

  @protected
  TunnelConfig sse_decode_tunnel_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_forwardType = sse_decode_tunnel_forward_type(deserializer);
    var var_sshProfileId = sse_decode_String(deserializer);
    var var_listenHost = sse_decode_String(deserializer);
    var var_listenPort = sse_decode_u_16(deserializer);
    var var_targetHost = sse_decode_String(deserializer);
    var var_targetPort = sse_decode_u_16(deserializer);
    var var_status = sse_decode_tunnel_runtime_status(deserializer);
    return TunnelConfig(
      id: var_id,
      name: var_name,
      forwardType: var_forwardType,
      sshProfileId: var_sshProfileId,
      listenHost: var_listenHost,
      listenPort: var_listenPort,
      targetHost: var_targetHost,
      targetPort: var_targetPort,
      status: var_status,
    );
  }

  @protected
  TunnelForwardType sse_decode_tunnel_forward_type(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return TunnelForwardType.values[inner];
  }

  @protected
  TunnelRuntimeStatus sse_decode_tunnel_runtime_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return TunnelRuntimeStatus.values[inner];
  }

  @protected
  TunnelStartResult sse_decode_tunnel_start_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_tunnel = sse_decode_opt_box_autoadd_tunnel_config(deserializer);
    var var_error = sse_decode_opt_box_autoadd_ssh_connect_error(deserializer);
    return TunnelStartResult(tunnel: var_tunnel, error: var_error);
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  UiTheme sse_decode_ui_theme(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_presetName = sse_decode_String(deserializer);
    var var_fontFamily = sse_decode_String(deserializer);
    var var_fontSize = sse_decode_u_32(deserializer);
    var var_normalFontWeight = sse_decode_u_32(deserializer);
    var var_boldFontWeight = sse_decode_u_32(deserializer);
    var var_background = sse_decode_String(deserializer);
    var var_panel = sse_decode_String(deserializer);
    var var_sidebar = sse_decode_String(deserializer);
    var var_accent = sse_decode_String(deserializer);
    var var_textPrimary = sse_decode_String(deserializer);
    var var_textMuted = sse_decode_String(deserializer);
    return UiTheme(
      presetName: var_presetName,
      fontFamily: var_fontFamily,
      fontSize: var_fontSize,
      normalFontWeight: var_normalFontWeight,
      boldFontWeight: var_boldFontWeight,
      background: var_background,
      panel: var_panel,
      sidebar: var_sidebar,
      accent: var_accent,
      textPrimary: var_textPrimary,
      textMuted: var_textMuted,
    );
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_list_prim_u_8_strict_Sse(
    RustStreamSink<Uint8List> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_ssh_auth_credential(
    SshAuthCredential self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ssh_auth_credential(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_ssh_connect_error(
    SshConnectError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ssh_connect_error(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_ssh_session(
    SshSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ssh_session(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_theme_settings(
    ThemeSettings self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_theme_settings(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_tunnel_config(
    TunnelConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_tunnel_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_regex_highlight(
    List<RegexHighlight> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_regex_highlight(item, serializer);
    }
  }

  @protected
  void sse_encode_list_ssh_profile(
    List<SshProfile> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_ssh_profile(item, serializer);
    }
  }

  @protected
  void sse_encode_list_tunnel_config(
    List<TunnelConfig> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_tunnel_config(item, serializer);
    }
  }

  @protected
  void sse_encode_local_terminal_session(
    LocalTerminalSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sessionId, serializer);
    sse_encode_String(self.title, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_ssh_connect_error(
    SshConnectError? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_ssh_connect_error(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_ssh_session(
    SshSession? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_ssh_session(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_tunnel_config(
    TunnelConfig? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_tunnel_config(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_16(self, serializer);
    }
  }

  @protected
  void sse_encode_regex_highlight(
    RegexHighlight self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.pattern, serializer);
    sse_encode_String(self.color, serializer);
    sse_encode_String(self.note, serializer);
  }

  @protected
  void sse_encode_ssh_auth_credential(
    SshAuthCredential self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.password, serializer);
    sse_encode_opt_String(self.privateKeyPath, serializer);
    sse_encode_opt_String(self.passphrase, serializer);
  }

  @protected
  void sse_encode_ssh_auth_mode(SshAuthMode self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_ssh_connect_error(
    SshConnectError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ssh_connect_error_code(self.code, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_ssh_connect_error_code(
    SshConnectErrorCode self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_ssh_connect_result(
    SshConnectResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_ssh_session(self.session, serializer);
    sse_encode_opt_box_autoadd_ssh_connect_error(self.error, serializer);
  }

  @protected
  void sse_encode_ssh_profile(SshProfile self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.host, serializer);
    sse_encode_u_16(self.port, serializer);
    sse_encode_String(self.username, serializer);
    sse_encode_ssh_auth_mode(self.authMode, serializer);
    sse_encode_String(self.password, serializer);
    sse_encode_String(self.privateKeyPath, serializer);
    sse_encode_String(self.termType, serializer);
  }

  @protected
  void sse_encode_ssh_session(SshSession self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sessionId, serializer);
    sse_encode_String(self.profileId, serializer);
    sse_encode_String(self.connectionId, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_u_16(self.rows, serializer);
    sse_encode_u_16(self.cols, serializer);
    sse_encode_String(self.termType, serializer);
  }

  @protected
  void sse_encode_terminal_theme(TerminalTheme self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.presetName, serializer);
    sse_encode_String(self.fontFamily, serializer);
    sse_encode_u_32(self.fontSize, serializer);
    sse_encode_u_32(self.normalFontWeight, serializer);
    sse_encode_u_32(self.boldFontWeight, serializer);
    sse_encode_String(self.cursorStyle, serializer);
    sse_encode_bool(self.cursorBlink, serializer);
    sse_encode_String(self.foreground, serializer);
    sse_encode_String(self.terminalBackground, serializer);
    sse_encode_String(self.selectionColor, serializer);
    sse_encode_String(self.cursorColor, serializer);
    sse_encode_u_32(self.scrollbackLines, serializer);
    sse_encode_list_regex_highlight(self.regexHighlights, serializer);
  }

  @protected
  void sse_encode_theme_settings(ThemeSettings self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ui_theme(self.ui, serializer);
    sse_encode_terminal_theme(self.terminal, serializer);
  }

  @protected
  void sse_encode_tunnel_config(TunnelConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_tunnel_forward_type(self.forwardType, serializer);
    sse_encode_String(self.sshProfileId, serializer);
    sse_encode_String(self.listenHost, serializer);
    sse_encode_u_16(self.listenPort, serializer);
    sse_encode_String(self.targetHost, serializer);
    sse_encode_u_16(self.targetPort, serializer);
    sse_encode_tunnel_runtime_status(self.status, serializer);
  }

  @protected
  void sse_encode_tunnel_forward_type(
    TunnelForwardType self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_tunnel_runtime_status(
    TunnelRuntimeStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_tunnel_start_result(
    TunnelStartResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_tunnel_config(self.tunnel, serializer);
    sse_encode_opt_box_autoadd_ssh_connect_error(self.error, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_ui_theme(UiTheme self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.presetName, serializer);
    sse_encode_String(self.fontFamily, serializer);
    sse_encode_u_32(self.fontSize, serializer);
    sse_encode_u_32(self.normalFontWeight, serializer);
    sse_encode_u_32(self.boldFontWeight, serializer);
    sse_encode_String(self.background, serializer);
    sse_encode_String(self.panel, serializer);
    sse_encode_String(self.sidebar, serializer);
    sse_encode_String(self.accent, serializer);
    sse_encode_String(self.textPrimary, serializer);
    sse_encode_String(self.textMuted, serializer);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
