// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'profile.dart';
import 'ssh_session.dart';
import 'theme.dart';
import 'tunnel.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<Uint8List> dco_decode_StreamSink_list_prim_u_8_strict_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ThemeSettings dco_decode_box_autoadd_theme_settings(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RegexHighlight> dco_decode_list_regex_highlight(dynamic raw);

  @protected
  List<SshProfile> dco_decode_list_ssh_profile(dynamic raw);

  @protected
  List<TunnelConfig> dco_decode_list_tunnel_config(dynamic raw);

  @protected
  RegexHighlight dco_decode_regex_highlight(dynamic raw);

  @protected
  SshProfile dco_decode_ssh_profile(dynamic raw);

  @protected
  SshSession dco_decode_ssh_session(dynamic raw);

  @protected
  TerminalTheme dco_decode_terminal_theme(dynamic raw);

  @protected
  ThemeSettings dco_decode_theme_settings(dynamic raw);

  @protected
  TunnelConfig dco_decode_tunnel_config(dynamic raw);

  @protected
  TunnelForwardType dco_decode_tunnel_forward_type(dynamic raw);

  @protected
  TunnelRuntimeStatus dco_decode_tunnel_runtime_status(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  UiTheme dco_decode_ui_theme(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<Uint8List> sse_decode_StreamSink_list_prim_u_8_strict_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ThemeSettings sse_decode_box_autoadd_theme_settings(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RegexHighlight> sse_decode_list_regex_highlight(
    SseDeserializer deserializer,
  );

  @protected
  List<SshProfile> sse_decode_list_ssh_profile(SseDeserializer deserializer);

  @protected
  List<TunnelConfig> sse_decode_list_tunnel_config(
    SseDeserializer deserializer,
  );

  @protected
  RegexHighlight sse_decode_regex_highlight(SseDeserializer deserializer);

  @protected
  SshProfile sse_decode_ssh_profile(SseDeserializer deserializer);

  @protected
  SshSession sse_decode_ssh_session(SseDeserializer deserializer);

  @protected
  TerminalTheme sse_decode_terminal_theme(SseDeserializer deserializer);

  @protected
  ThemeSettings sse_decode_theme_settings(SseDeserializer deserializer);

  @protected
  TunnelConfig sse_decode_tunnel_config(SseDeserializer deserializer);

  @protected
  TunnelForwardType sse_decode_tunnel_forward_type(
    SseDeserializer deserializer,
  );

  @protected
  TunnelRuntimeStatus sse_decode_tunnel_runtime_status(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  UiTheme sse_decode_ui_theme(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_list_prim_u_8_strict_Sse(
    RustStreamSink<Uint8List> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_theme_settings(
    ThemeSettings self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_regex_highlight(
    List<RegexHighlight> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ssh_profile(
    List<SshProfile> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_tunnel_config(
    List<TunnelConfig> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_regex_highlight(
    RegexHighlight self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ssh_profile(SshProfile self, SseSerializer serializer);

  @protected
  void sse_encode_ssh_session(SshSession self, SseSerializer serializer);

  @protected
  void sse_encode_terminal_theme(TerminalTheme self, SseSerializer serializer);

  @protected
  void sse_encode_theme_settings(ThemeSettings self, SseSerializer serializer);

  @protected
  void sse_encode_tunnel_config(TunnelConfig self, SseSerializer serializer);

  @protected
  void sse_encode_tunnel_forward_type(
    TunnelForwardType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_tunnel_runtime_status(
    TunnelRuntimeStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_ui_theme(UiTheme self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
