// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `cleanup_session_after_loop`, `command_exists`, `default_shell_for_platform`, `default_shell`, `home_dir`, `pty_size_from`, `push_output`, `run_command_loop`, `run_output_loop`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `LocalTerminalCommand`, `LocalTerminalHandle`, `ShellPlatform`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`

Future<LocalTerminalSession> spawnLocalTerminal({int? rows, int? cols}) =>
    RustLib.instance.api.crateLocalTerminalSpawnLocalTerminal(
      rows: rows,
      cols: cols,
    );

Stream<Uint8List> createLocalTerminalOutputStream({
  required String sessionId,
}) => RustLib.instance.api.crateLocalTerminalCreateLocalTerminalOutputStream(
  sessionId: sessionId,
);

Future<void> writeToLocalTerminal({
  required String sessionId,
  required List<int> data,
}) => RustLib.instance.api.crateLocalTerminalWriteToLocalTerminal(
  sessionId: sessionId,
  data: data,
);

Future<void> resizeLocalTerminal({
  required String sessionId,
  required int rows,
  required int cols,
}) => RustLib.instance.api.crateLocalTerminalResizeLocalTerminal(
  sessionId: sessionId,
  rows: rows,
  cols: cols,
);

Future<void> closeLocalTerminal({required String sessionId}) => RustLib
    .instance
    .api
    .crateLocalTerminalCloseLocalTerminal(sessionId: sessionId);

class LocalTerminalSession {
  final String sessionId;
  final String title;

  const LocalTerminalSession({required this.sessionId, required this.title});

  @override
  int get hashCode => sessionId.hashCode ^ title.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalTerminalSession &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          title == other.title;
}
