// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `capture_stats`, `collect_mimalloc_stats`, `collect_process_info`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<RustMemSnapshot> rustMemSnapshot() =>
    RustLib.instance.api.crateMemMetricsRustMemSnapshot();

Future<void> rustMimallocCollect() =>
    RustLib.instance.api.crateMemMetricsRustMimallocCollect();

class RustMemSnapshot {
  final BigInt currentRss;
  final BigInt peakRss;
  final BigInt currentCommit;
  final BigInt peakCommit;
  final BigInt pageFaults;
  final BigInt elapsedMs;
  final BigInt userMs;
  final BigInt systemMs;
  final BigInt sshSessions;
  final BigInt sshConnections;
  final BigInt sshClients;
  final BigInt localTerminals;
  final BigInt tunnelConfigs;
  final BigInt tunnelsRunning;
  final String mimallocStatsText;

  const RustMemSnapshot({
    required this.currentRss,
    required this.peakRss,
    required this.currentCommit,
    required this.peakCommit,
    required this.pageFaults,
    required this.elapsedMs,
    required this.userMs,
    required this.systemMs,
    required this.sshSessions,
    required this.sshConnections,
    required this.sshClients,
    required this.localTerminals,
    required this.tunnelConfigs,
    required this.tunnelsRunning,
    required this.mimallocStatsText,
  });

  @override
  int get hashCode =>
      currentRss.hashCode ^
      peakRss.hashCode ^
      currentCommit.hashCode ^
      peakCommit.hashCode ^
      pageFaults.hashCode ^
      elapsedMs.hashCode ^
      userMs.hashCode ^
      systemMs.hashCode ^
      sshSessions.hashCode ^
      sshConnections.hashCode ^
      sshClients.hashCode ^
      localTerminals.hashCode ^
      tunnelConfigs.hashCode ^
      tunnelsRunning.hashCode ^
      mimallocStatsText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustMemSnapshot &&
          runtimeType == other.runtimeType &&
          currentRss == other.currentRss &&
          peakRss == other.peakRss &&
          currentCommit == other.currentCommit &&
          peakCommit == other.peakCommit &&
          pageFaults == other.pageFaults &&
          elapsedMs == other.elapsedMs &&
          userMs == other.userMs &&
          systemMs == other.systemMs &&
          sshSessions == other.sshSessions &&
          sshConnections == other.sshConnections &&
          sshClients == other.sshClients &&
          localTerminals == other.localTerminals &&
          tunnelConfigs == other.tunnelConfigs &&
          tunnelsRunning == other.tunnelsRunning &&
          mimallocStatsText == other.mimallocStatsText;
}
