// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `default_auth_mode`, `default_term_type`, `ensure_profiles_loaded`, `into_profile_with_migration`, `load_profiles_from_disk`, `write_profiles_to_disk`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ProfileStore`, `SshProfileConfig`, `SshProfilesFile`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `from`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`, `default`

Future<List<SshProfile>> listProfiles() =>
    RustLib.instance.api.crateProfileListProfiles();

Future<SshProfile> createProfile({
  required String name,
  required String host,
  required int port,
  required String username,
  required SshAuthMode authMode,
  required String password,
  required String privateKeyPath,
  required String termType,
}) => RustLib.instance.api.crateProfileCreateProfile(
  name: name,
  host: host,
  port: port,
  username: username,
  authMode: authMode,
  password: password,
  privateKeyPath: privateKeyPath,
  termType: termType,
);

Future<SshProfile> updateProfile({
  required String id,
  required String name,
  required String host,
  required int port,
  required String username,
  required SshAuthMode authMode,
  required String password,
  required String privateKeyPath,
  required String termType,
}) => RustLib.instance.api.crateProfileUpdateProfile(
  id: id,
  name: name,
  host: host,
  port: port,
  username: username,
  authMode: authMode,
  password: password,
  privateKeyPath: privateKeyPath,
  termType: termType,
);

Future<void> deleteProfile({required String id}) =>
    RustLib.instance.api.crateProfileDeleteProfile(id: id);

enum SshAuthMode { password, privateKey }

class SshProfile {
  final String id;
  final String name;
  final String host;
  final int port;
  final String username;
  final SshAuthMode authMode;
  final String password;
  final String privateKeyPath;
  final String termType;

  const SshProfile({
    required this.id,
    required this.name,
    required this.host,
    required this.port,
    required this.username,
    required this.authMode,
    required this.password,
    required this.privateKeyPath,
    required this.termType,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      host.hashCode ^
      port.hashCode ^
      username.hashCode ^
      authMode.hashCode ^
      password.hashCode ^
      privateKeyPath.hashCode ^
      termType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SshProfile &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          host == other.host &&
          port == other.port &&
          username == other.username &&
          authMode == other.authMode &&
          password == other.password &&
          privateKeyPath == other.privateKeyPath &&
          termType == other.termType;
}
