// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`

Future<List<SshProfile>> listProfiles() =>
    RustLib.instance.api.crateProfileListProfiles();

Future<SshProfile> createProfile({
  required String name,
  required String host,
  required int port,
  required String username,
  required String password,
}) => RustLib.instance.api.crateProfileCreateProfile(
  name: name,
  host: host,
  port: port,
  username: username,
  password: password,
);

Future<SshProfile> updateProfile({
  required String id,
  required String name,
  required String host,
  required int port,
  required String username,
  required String password,
}) => RustLib.instance.api.crateProfileUpdateProfile(
  id: id,
  name: name,
  host: host,
  port: port,
  username: username,
  password: password,
);

Future<void> deleteProfile({required String id}) =>
    RustLib.instance.api.crateProfileDeleteProfile(id: id);

class SshProfile {
  final String id;
  final String name;
  final String host;
  final int port;
  final String username;
  final String password;

  const SshProfile({
    required this.id,
    required this.name,
    required this.host,
    required this.port,
    required this.username,
    required this.password,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      host.hashCode ^
      port.hashCode ^
      username.hashCode ^
      password.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SshProfile &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          host == other.host &&
          port == other.port &&
          username == other.username &&
          password == other.password;
}
