// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `push_output`, `run_session_loop`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SshClientHandler`, `SshCommand`, `SshConnection`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `check_server_key`, `clone`, `clone`, `eq`, `fmt`

Stream<Uint8List> createOutputStream({required String sessionId}) => RustLib
    .instance
    .api
    .crateSshSessionCreateOutputStream(sessionId: sessionId);

Future<SshSession> connectProfile({
  required String profileId,
  required String title,
  required String host,
  required int port,
  required String username,
  required String password,
}) => RustLib.instance.api.crateSshSessionConnectProfile(
  profileId: profileId,
  title: title,
  host: host,
  port: port,
  username: username,
  password: password,
);

Future<void> writeToSession({
  required String sessionId,
  required List<int> data,
}) => RustLib.instance.api.crateSshSessionWriteToSession(
  sessionId: sessionId,
  data: data,
);

Future<void> resizeSession({
  required String sessionId,
  required int rows,
  required int cols,
}) => RustLib.instance.api.crateSshSessionResizeSession(
  sessionId: sessionId,
  rows: rows,
  cols: cols,
);

Future<bool> closeSession({required String sessionId}) =>
    RustLib.instance.api.crateSshSessionCloseSession(sessionId: sessionId);

class SshSession {
  final String sessionId;
  final String profileId;
  final String title;
  final int rows;
  final int cols;

  const SshSession({
    required this.sessionId,
    required this.profileId,
    required this.title,
    required this.rows,
    required this.cols,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      profileId.hashCode ^
      title.hashCode ^
      rows.hashCode ^
      cols.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SshSession &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          profileId == other.profileId &&
          title == other.title &&
          rows == other.rows &&
          cols == other.cols;
}
