// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `authenticate`, `connect_error`, `load_private_key`

class SshAuthCredential {
  final String? password;
  final String? privateKeyPath;
  final String? passphrase;

  const SshAuthCredential({
    this.password,
    this.privateKeyPath,
    this.passphrase,
  });

  @override
  int get hashCode =>
      password.hashCode ^ privateKeyPath.hashCode ^ passphrase.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SshAuthCredential &&
          runtimeType == other.runtimeType &&
          password == other.password &&
          privateKeyPath == other.privateKeyPath &&
          passphrase == other.passphrase;
}

class SshConnectError {
  final SshConnectErrorCode code;
  final String message;

  const SshConnectError({required this.code, required this.message});

  @override
  int get hashCode => code.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SshConnectError &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message;
}

enum SshConnectErrorCode {
  passphraseRequired,
  privateKeyFileUnreadable,
  invalidPrivateKey,
  authenticationFailed,
  connectionFailed,
  channelFailed,
  ptyFailed,
}
