// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `default_theme`, `ensure_theme_loaded`, `load_theme_from_disk`, `write_theme_to_disk`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `RegexHighlightConfig`, `TerminalThemeConfig`, `ThemeFile`, `ThemeStore`, `UiThemeConfig`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`

Future<ThemeSettings> loadTheme() => RustLib.instance.api.crateThemeLoadTheme();

Future<void> saveTheme({required ThemeSettings settings}) =>
    RustLib.instance.api.crateThemeSaveTheme(settings: settings);

class RegexHighlight {
  final String pattern;
  final String color;
  final String note;

  const RegexHighlight({
    required this.pattern,
    required this.color,
    required this.note,
  });

  @override
  int get hashCode => pattern.hashCode ^ color.hashCode ^ note.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RegexHighlight &&
          runtimeType == other.runtimeType &&
          pattern == other.pattern &&
          color == other.color &&
          note == other.note;
}

class TerminalTheme {
  final String presetName;
  final String fontFamily;
  final int fontSize;
  final String cursorStyle;
  final bool cursorBlink;
  final String foreground;
  final String terminalBackground;
  final String selectionColor;
  final String cursorColor;
  final int scrollbackLines;
  final List<RegexHighlight> regexHighlights;

  const TerminalTheme({
    required this.presetName,
    required this.fontFamily,
    required this.fontSize,
    required this.cursorStyle,
    required this.cursorBlink,
    required this.foreground,
    required this.terminalBackground,
    required this.selectionColor,
    required this.cursorColor,
    required this.scrollbackLines,
    required this.regexHighlights,
  });

  @override
  int get hashCode =>
      presetName.hashCode ^
      fontFamily.hashCode ^
      fontSize.hashCode ^
      cursorStyle.hashCode ^
      cursorBlink.hashCode ^
      foreground.hashCode ^
      terminalBackground.hashCode ^
      selectionColor.hashCode ^
      cursorColor.hashCode ^
      scrollbackLines.hashCode ^
      regexHighlights.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TerminalTheme &&
          runtimeType == other.runtimeType &&
          presetName == other.presetName &&
          fontFamily == other.fontFamily &&
          fontSize == other.fontSize &&
          cursorStyle == other.cursorStyle &&
          cursorBlink == other.cursorBlink &&
          foreground == other.foreground &&
          terminalBackground == other.terminalBackground &&
          selectionColor == other.selectionColor &&
          cursorColor == other.cursorColor &&
          scrollbackLines == other.scrollbackLines &&
          regexHighlights == other.regexHighlights;
}

class ThemeSettings {
  final UiTheme ui;
  final TerminalTheme terminal;

  const ThemeSettings({required this.ui, required this.terminal});

  @override
  int get hashCode => ui.hashCode ^ terminal.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ThemeSettings &&
          runtimeType == other.runtimeType &&
          ui == other.ui &&
          terminal == other.terminal;
}

class UiTheme {
  final String presetName;
  final String fontFamily;
  final int fontSize;
  final String background;
  final String panel;
  final String sidebar;
  final String accent;
  final String textPrimary;
  final String textMuted;

  const UiTheme({
    required this.presetName,
    required this.fontFamily,
    required this.fontSize,
    required this.background,
    required this.panel,
    required this.sidebar,
    required this.accent,
    required this.textPrimary,
    required this.textMuted,
  });

  @override
  int get hashCode =>
      presetName.hashCode ^
      fontFamily.hashCode ^
      fontSize.hashCode ^
      background.hashCode ^
      panel.hashCode ^
      sidebar.hashCode ^
      accent.hashCode ^
      textPrimary.hashCode ^
      textMuted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiTheme &&
          runtimeType == other.runtimeType &&
          presetName == other.presetName &&
          fontFamily == other.fontFamily &&
          fontSize == other.fontSize &&
          background == other.background &&
          panel == other.panel &&
          sidebar == other.sidebar &&
          accent == other.accent &&
          textPrimary == other.textPrimary &&
          textMuted == other.textMuted;
}
