// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'ssh_auth.dart';

// These functions are ignored because they are not marked as `pub`: `connect_ssh_profile`, `ensure_tunnels_loaded`, `handle_local_tunnel_connection`, `into_config_with_migration`, `load_tunnels_from_disk`, `local_tcp_port_is_open`, `next_backoff_delay`, `relay_tcp_stream_and_channel`, `remote_route_key`, `remote_target_is_open_via_ssh`, `run_local_tunnel`, `run_remote_tunnel`, `run_tunnel`, `runtime_status`, `set_runtime_status`, `tunnel_start_failure`, `tunnel_start_success`, `with_runtime_status`, `write_tunnels_to_disk`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `RemoteRoute`, `TunnelClientHandler`, `TunnelConfigFile`, `TunnelForwardTypeFile`, `TunnelRuntime`, `TunnelStore`, `TunnelsFile`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `check_server_key`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `server_channel_open_forwarded_tcpip`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`, `default`

Future<List<TunnelConfig>> listTunnels() =>
    RustLib.instance.api.crateTunnelListTunnels();

Future<TunnelConfig> createTunnel({
  required String name,
  required TunnelForwardType forwardType,
  required String sshProfileId,
  required String listenHost,
  required int listenPort,
  required String targetHost,
  required int targetPort,
}) => RustLib.instance.api.crateTunnelCreateTunnel(
  name: name,
  forwardType: forwardType,
  sshProfileId: sshProfileId,
  listenHost: listenHost,
  listenPort: listenPort,
  targetHost: targetHost,
  targetPort: targetPort,
);

Future<TunnelConfig> updateTunnel({
  required String id,
  required String name,
  required TunnelForwardType forwardType,
  required String sshProfileId,
  required String listenHost,
  required int listenPort,
  required String targetHost,
  required int targetPort,
}) => RustLib.instance.api.crateTunnelUpdateTunnel(
  id: id,
  name: name,
  forwardType: forwardType,
  sshProfileId: sshProfileId,
  listenHost: listenHost,
  listenPort: listenPort,
  targetHost: targetHost,
  targetPort: targetPort,
);

Future<void> deleteTunnel({required String id}) =>
    RustLib.instance.api.crateTunnelDeleteTunnel(id: id);

Future<TunnelStartResult> startTunnel({
  required String id,
  required SshAuthCredential credential,
}) =>
    RustLib.instance.api.crateTunnelStartTunnel(id: id, credential: credential);

Future<TunnelConfig> stopTunnel({required String id}) =>
    RustLib.instance.api.crateTunnelStopTunnel(id: id);

class TunnelConfig {
  final String id;
  final String name;
  final TunnelForwardType forwardType;
  final String sshProfileId;
  final String listenHost;
  final int listenPort;
  final String targetHost;
  final int targetPort;
  final TunnelRuntimeStatus status;

  const TunnelConfig({
    required this.id,
    required this.name,
    required this.forwardType,
    required this.sshProfileId,
    required this.listenHost,
    required this.listenPort,
    required this.targetHost,
    required this.targetPort,
    required this.status,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      forwardType.hashCode ^
      sshProfileId.hashCode ^
      listenHost.hashCode ^
      listenPort.hashCode ^
      targetHost.hashCode ^
      targetPort.hashCode ^
      status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TunnelConfig &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          forwardType == other.forwardType &&
          sshProfileId == other.sshProfileId &&
          listenHost == other.listenHost &&
          listenPort == other.listenPort &&
          targetHost == other.targetHost &&
          targetPort == other.targetPort &&
          status == other.status;
}

enum TunnelForwardType { local, remote }

enum TunnelRuntimeStatus { stopped, waiting, forwarding }

class TunnelStartResult {
  final TunnelConfig? tunnel;
  final SshConnectError? error;

  const TunnelStartResult({this.tunnel, this.error});

  @override
  int get hashCode => tunnel.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TunnelStartResult &&
          runtimeType == other.runtimeType &&
          tunnel == other.tunnel &&
          error == other.error;
}
